import type { PublicAuthor, PublicComment, PublicWork } from "@/lib/social-types"

export const SEED_AUTHORS: PublicAuthor[] = [
  {
    username: "noah.held",
    displayName: "Noah Held",
    tagline: "Sodium lamps. Wet asphalt. One coat.",
    avatarUrl: null,
  },
  {
    username: "mira.cut",
    displayName: "Mira Cut",
    tagline: "Hold the still. Then move it.",
    avatarUrl: null,
  },
  {
    username: "kenji.frame",
    displayName: "Kenji Frame",
    tagline: "One light. One street. No swarm.",
    avatarUrl: null,
  },
  {
    username: "ada.tape",
    displayName: "Ada Tape",
    tagline: "Clips that sit still first.",
    avatarUrl: null,
  },
  {
    username: "rafi.desk",
    displayName: "Rafi Desk",
    tagline: "Print grain, then the cut.",
    avatarUrl: null,
  },
]

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString()

const author = (username: string): PublicAuthor =>
  SEED_AUTHORS.find((a) => a.username === username) ?? SEED_AUTHORS[0]!

export const SEED_WORKS: PublicWork[] = [
  {
    slug: "wet-street-dusk",
    kind: "image",
    prompt: "A wet street at dusk, sodium lamps, one figure in a cobalt coat",
    tagline: "The coat is the only warm thing on the block.",
    ratio: "16:9",
    paper: "held",
    palette: ["#2F5BFF", "#12151C", "#E8A317"],
    likeCount: 128,
    commentCount: 2,
    featured: true,
    createdAt: daysAgo(1),
    author: author("noah.held"),
  },
  {
    slug: "train-window-night",
    kind: "video",
    prompt: "A train window at night, reflections sliding, one amber interior light",
    tagline: "Eight seconds of glass and someone else’s kitchen.",
    ratio: "16:9",
    motion: "pan",
    length: "8s",
    palette: ["#E8A317", "#1A1E28", "#2F5BFF"],
    likeCount: 96,
    commentCount: 2,
    featured: true,
    createdAt: daysAgo(2),
    author: author("mira.cut"),
  },
  {
    slug: "interior-held-light",
    kind: "image",
    prompt: "Empty diner booth, held tungsten, a newspaper folded once",
    tagline: "Nobody sat. The light still waited.",
    ratio: "4:3",
    paper: "studio",
    palette: ["#E8A317", "#12151C", "#F3F0EA"],
    likeCount: 74,
    commentCount: 1,
    featured: false,
    createdAt: daysAgo(3),
    author: author("kenji.frame"),
  },
  {
    slug: "orbit-warehouse",
    kind: "video",
    prompt: "Slow orbit around a warehouse door, rain on corrugated steel, one red bulb",
    tagline: "The door never opens. The camera does the work.",
    ratio: "16:9",
    motion: "orbit",
    length: "12s",
    palette: ["#FF4D3A", "#12151C", "#9AA3B5"],
    likeCount: 61,
    commentCount: 1,
    featured: false,
    createdAt: daysAgo(4),
    author: author("ada.tape"),
  },
  {
    slug: "print-grain-portrait",
    kind: "image",
    prompt: "Close portrait, print grain, chalk wall, saffron scarf",
    tagline: "Grain first. Face second.",
    ratio: "1:1",
    paper: "film",
    palette: ["#F3F0EA", "#12151C", "#E8A317"],
    likeCount: 88,
    commentCount: 1,
    featured: false,
    createdAt: daysAgo(5),
    author: author("rafi.desk"),
  },
  {
    slug: "push-in-kitchen",
    kind: "video",
    prompt: "Push in on a midnight kitchen, steam, one cobalt mug",
    tagline: "Four seconds. That’s the whole house.",
    ratio: "9:16",
    motion: "push",
    length: "4s",
    palette: ["#2F5BFF", "#1A1E28", "#F3F0EA"],
    likeCount: 53,
    commentCount: 0,
    featured: false,
    createdAt: daysAgo(5),
    author: author("mira.cut"),
  },
  {
    slug: "night-street-phone",
    kind: "image",
    prompt: "Night street, phone-tall frame, one shop sign in coral",
    tagline: "Made for the hand. Still a still.",
    ratio: "9:16",
    paper: "night",
    palette: ["#FF4D3A", "#12151C", "#2F5BFF"],
    likeCount: 41,
    commentCount: 0,
    featured: false,
    createdAt: daysAgo(6),
    author: author("noah.held"),
  },
  {
    slug: "locked-cam-lobby",
    kind: "video",
    prompt: "Locked camera in a hotel lobby at 3am, one suitcase, fluorescent hold",
    tagline: "Nothing moves except the clock you cannot see.",
    ratio: "16:9",
    motion: "lock",
    length: "8s",
    palette: ["#9AA3B5", "#12151C", "#E8A317"],
    likeCount: 39,
    commentCount: 1,
    featured: false,
    createdAt: daysAgo(7),
    author: author("ada.tape"),
  },
  {
    slug: "studio-pack-shoes",
    kind: "image",
    prompt: "Studio pack, two shoes on seamless, hard shadow, cobalt seamless",
    tagline: "Product without the catalogue voice.",
    ratio: "1:1",
    paper: "studio",
    palette: ["#2F5BFF", "#F3F0EA", "#12151C"],
    likeCount: 57,
    commentCount: 0,
    featured: false,
    createdAt: daysAgo(8),
    author: author("kenji.frame"),
  },
  {
    slug: "dissolve-harbor",
    kind: "video",
    prompt: "Harbor at blue hour, slow pan along wet rope, fog horn far off",
    tagline: "Sound implied. Picture held.",
    ratio: "16:9",
    motion: "pan",
    length: "12s",
    palette: ["#1A1E28", "#2F5BFF", "#9AA3B5"],
    likeCount: 45,
    commentCount: 0,
    featured: false,
    createdAt: daysAgo(9),
    author: author("rafi.desk"),
  },
  {
    slug: "chalk-wall-mark",
    kind: "image",
    prompt: "Chalk wall, one geometric F mark in cobalt, hard edge, no drop shadow",
    tagline: "The desk’s own letter.",
    ratio: "4:3",
    paper: "held",
    palette: ["#F3F0EA", "#2F5BFF", "#12151C"],
    likeCount: 102,
    commentCount: 1,
    featured: true,
    createdAt: daysAgo(2),
    author: author("kenji.frame"),
  },
  {
    slug: "corridor-push",
    kind: "video",
    prompt: "Push down a concrete corridor, exit sign saffron, footsteps off-frame",
    tagline: "You are already late. The clip knows.",
    ratio: "9:16",
    motion: "push",
    length: "8s",
    palette: ["#E8A317", "#12151C", "#FF4D3A"],
    likeCount: 33,
    commentCount: 0,
    featured: false,
    createdAt: daysAgo(10),
    author: author("mira.cut"),
  },
]

export const SEED_COMMENTS: Array<PublicComment & { slug: string }> = [
  {
    slug: "wet-street-dusk",
    id: "c-wet-1",
    body: "The cobalt coat is doing all the talking. Keep the lamps mean.",
    createdAt: daysAgo(1),
    author: { username: "mira.cut", displayName: "Mira Cut", avatarUrl: null },
  },
  {
    slug: "wet-street-dusk",
    id: "c-wet-2",
    body: "I ran this prompt on held paper. Came back colder. Yours is the one.",
    createdAt: daysAgo(0.5),
    author: { username: "rafi.desk", displayName: "Rafi Desk", avatarUrl: null },
  },
  {
    slug: "train-window-night",
    id: "c-train-1",
    body: "The amber interior is the whole story. Don’t add a face.",
    createdAt: daysAgo(1.5),
    author: { username: "noah.held", displayName: "Noah Held", avatarUrl: null },
  },
  {
    slug: "train-window-night",
    id: "c-train-2",
    body: "Eight seconds is the right length. Twelve would explain too much.",
    createdAt: daysAgo(1),
    author: { username: "ada.tape", displayName: "Ada Tape", avatarUrl: null },
  },
  {
    slug: "interior-held-light",
    id: "c-diner-1",
    body: "Newspaper folded once is a better actor than a person here.",
    createdAt: daysAgo(2),
    author: { username: "ada.tape", displayName: "Ada Tape", avatarUrl: null },
  },
  {
    slug: "orbit-warehouse",
    id: "c-orbit-1",
    body: "Red bulb, rain, orbit — this is a cut-desk clip waiting for a still.",
    createdAt: daysAgo(3),
    author: { username: "kenji.frame", displayName: "Kenji Frame", avatarUrl: null },
  },
  {
    slug: "print-grain-portrait",
    id: "c-grain-1",
    body: "Scarf is saffron, wall is chalk. That’s the palette. Done.",
    createdAt: daysAgo(4),
    author: { username: "noah.held", displayName: "Noah Held", avatarUrl: null },
  },
  {
    slug: "locked-cam-lobby",
    id: "c-lobby-1",
    body: "Locked cam is harder than a pan. You held it.",
    createdAt: daysAgo(6),
    author: { username: "mira.cut", displayName: "Mira Cut", avatarUrl: null },
  },
  {
    slug: "chalk-wall-mark",
    id: "c-mark-1",
    body: "This belongs on the landing. Hard edge, no apology.",
    createdAt: daysAgo(1),
    author: { username: "rafi.desk", displayName: "Rafi Desk", avatarUrl: null },
  },
]
